name: CI-CD-Conversao-Temperatura
on:
  push:
    branches: [ conversao-temperatura-kubernetes-cloud ]
  workflow_dispatch:

jobs:
  ConversaoTemperatura-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Logout Docker
        run: docker logout

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
