name: CI-CD-Conversao-Temperatura
on:
  push:
    branches: [ conversao-temperatura-kubernetes-cloud ]
  workflow_dispatch:

jobs:
  ConversaoTemperatura-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Logout Docker
        run: docker logout

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
         context: ./src
         file: ./src/Dockerfile
         push: true
         tags: |
          marciozhu/conversao-temperatura:latest
          marciozhu/conversao-temperatura:v${{ github.run_number }}
          
  ConversaoTemperatura-CD:
    needs: [ ConversaoTemperatura-CI ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setting K8s Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
